blueprint:
  name: Automatic Hilo challenges with Schedule, Scenes
  description: Optimize your heating based on schedule,and Hilo challenges.
  domain: automation
  input:
    challenge_entity: input_text.phase_courante_des_defis
    scenes_normal_day:
      name: Normal daytime scenes (based on schedule)
      description: Temperature for times without a challenge (no reference, no appreciation).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_normal_night:
      name: Normal nighttime scenes (based on schedule)
      description: Temperature for times without a challenge (no reference, no appreciation).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_night_anchor:
      name: Hilo Challenge Anchor - Nighttime
      description: Temperature for 1am to 4am on challenge days (higher than normal) (significant impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_day_anchor:
      name: Hilo Challenge Anchor - Daytime
      description: Temperature for 12pm to 3pm on challenge days (higher than normal) (significant impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_night_higher:
      name: Morning reference scenes (6am - 10pm)
      description: Temperature for reference phases (higher than normal) (low impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_day_higher:
      name: Afternoon reference scenes (5pm - 8pm)
      description: Temperature for reference phases (higher than normal) (low impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_night_lower:
      name: Morning reference scenes (1:00am to 4:00am)
      description: Temperature for reference assessment phases (lower than normal) (moderate impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_day_lower:
      name: Daytime reference scenes (12pm to 3pm)
      description: Temperature for reference assessment phases (lower than normal) (moderate impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_preheat:
      name: Preheating Scene (5PM - 6PM & 4PM - 5PM)
      description: Température durant la phase de pré-chauffage (aucun impact sur les récompenses).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_ref_challenge_am:
      name: Scènes référence am (6:00 à 10:00)
      description: Température pour les phases de références (plus haute que la normale) (faible impact sur les récompenses).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_challenge_am:
      name: Scènes défi am (6:00 à 10:00)
      description: Température lors des défis (le plus bas possible).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_challenge_pm:
      name: Scènes défi pm (17:00 à 20:00)
      description: Température lors des défis (le plus bas possible).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
  source_url: https://raw.githubusercontent.com/TravisDee67/Home-Assistant/main/Blueprint.yaml
trigger:
  - platform: state
    entity_id: input_text.phase_courante_des_defis
  - platform: state
    entity_id:
      - schedule.daytime
condition: []
action:
  - if:
      - condition: state
        entity_id: schedule.daytime
        state: "on"
    then:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: ref_appreciation
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_daytime_lower
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: appreciation
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_daytime_higher
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: ref_challenge
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_anchor
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: challenge
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_reduce
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: preheat
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_preheat
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: normal
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.heating_daytime
                metadata: {}
    else:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: ref_appreciation
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_nighttime_lower
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: appreciation
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_nighttime_higher
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: ref_challenge
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_anchor
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: challenge
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_reduce
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: preheat
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_preheat
                metadata: {}
          - conditions:
              - condition: state
                entity_id: input_text.phase_courante_des_defis
                state: normal
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.hot_water_heater
              - service: scene.turn_on
                target:
                  entity_id: scene.heating_nighttime
                metadata: {}
mode: single
