blueprint:
  name: Défis Hilo automatiques
  description: Optimise les températures basées sur les défis Hilo
  domain: automation

  input:
    challenge_entity:
      name: Entité de phase de défi
      description: Input_text entity thas was manualy created
      selector:
        entity:
          domain: input_text

    challenge_am:
      name: Défi AM
      description: Va participer aux défis AM (incluant la référence)
      default: true
      selector:
        boolean:

    challenge_pm:
      name: Défi PM
      description: Va participer aux défis PM (incluant la référence)
      default: true
      selector:
        boolean:

    daytime_scene:
      name: Daytime Scene
      description: Va participer aux défis PM (incluant la référence)
      default: true
      selector:
        entity:
          domain: scene      

    thermostats:
      name: Thermostats
      selector:
        entity:
          domain: climate
          multiple: true

    water_heater:
      name: Water Heater (optionnel)
      description: Deactivates water heater during challenges and base reference phases
      default: null
      selector:
        entity:
          domain: switch

    normal_temp:
      name: Température normale
      description: Température pour les moments sans défis (ni référence, ni appréciation)
      default: 21
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    reference_temp:
      name: Température de référence
      description: Increase (plus haute que la normale) (faible impact sur les récompenses)
      default: 1.5
      selector:
        number:
          step: 0.5
          min: 0
          max: 10
          unit_of_measurement: °C

    appreciation_reference_temp:
      name: Température de la référence d'appréciation
      description: Température pour les phases d'appréciation de référence (plus basse que normale) (impact modéré sur les récompenses)
      default: 1.5
      selector:
        number:
          step: 0.5
          min: 0
          max: 10
          unit_of_measurement: °C

    appreciation_temp:
      name: Température de l'appréciation
      description: Température pour les phases d'appréciation (plus haute que normale) (impact important sur les récompenses)
      default: 1.5
      selector:
        number:
          step: 0.5
          min: 0
          max: 10
          unit_of_measurement: °C

    preheat_temp:
      name: Température de pré-chauffage
      description: Température durant la phase de pré-chauffage (aucun impact sur les récompenses)
      default: 1.5
      selector:
        number:
          step: 0.5
          min: 0
          max: 10
          unit_of_measurement: °C

    challenge_temp:
      name: Température de défi
      description: Température lors des défis (le plus bas possible)
      default: 1.5
      selector:
        number:
          step: 0.5
          min: 0
          max: 10
          unit_of_measurement: °C