blueprint:
  name: Automatic Hilo challenges with Schedule, Scenes
  description: Optimize your heating based on schedule,and Hilo challenges.
  domain: automation
  input:
    water_heater:
      name: Chauffe-eau (optionnel)
      description: Désactive le chauffe-eau durant les défis et les phases d'appréciation de référence
      default: null
      selector:
        entity:
          domain: switch
    challenge_entity:
      name: Entité de phase de défi
      description: Input_text entity thas was manualy created
      selector:
        entity:
          domain: input_text
    scenes_normal_day:
      name: Normal daytime scenes (based on schedule)
      description: Temperature for times without a challenge (no reference, no appreciation).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_normal_night:
      name: Normal nighttime scenes (based on schedule)
      description: Temperature for times without a challenge (no reference, no appreciation).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_night_higher:
      name: Morning challenge reference scenes (6am - 10pm)
      description: Temperature for reference phases (higher than normal) (low impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_day_higher:
      name: Afternoon challenge reference scenes (5pm - 8pm)
      description: Temperature for reference phases (higher than normal) (low impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_night_lower:
      name: Morning reference scenes (1am to 4am)
      description: Temperature for reference assessment phases (lower than normal) (moderate impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_day_lower:
      name: Afternoon reference scenes (12pm to 3pm)
      description: Temperature for reference assessment phases (lower than normal) (moderate impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_night_anchor:
      name: Hilo Challenge Anchor - Nighttime
      description: Temperature for 1am to 4am on challenge days (higher than normal) (significant impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_day_anchor:
      name: Hilo Challenge Anchor - Daytime
      description: Temperature for 12pm to 3pm on challenge days (higher than normal) (significant impact on rewards).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_preheat:
      name: Preheating Scene (5PM - 6PM & 4PM - 5PM)
      description: Température durant la phase de pré-chauffage (aucun impact sur les récompenses).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
    scenes_challenge:
      name: Scènes défi
      description: Température lors des défis (le plus bas possible).
      default:
      selector:
        entity:
          domain:
            - scene
          multiple: true
  source_url: https://raw.githubusercontent.com/TravisDee67/Home-Assistant/main/Blueprint.yaml
trigger:
  - platform: state
    entity_id: !input challenge_entity
  - platform: state
    entity_id:
      - schedule.daytime
condition: []
variables:
  water_heater: !input water_heater
action:
  - if:
      - condition: state
        entity_id: schedule.daytime
        state: "on"
    then:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: ref_appreciation
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_day_lower
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_off
                      data: {}
                      target:
                        entity_id: !input water_heater
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: appreciation
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_day_higher
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_on
                      data: {}
                      target:
                        entity_id: !input water_heater                
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: ref_challenge
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.hilo_anchor
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_on
                      data: {}
                      target:
                        entity_id: !input water_heater
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: challenge
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_challenge
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_off
                      data: {}
                      target:
                        entity_id: !input water_heater
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: preheat
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_preheat
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_on
                      data: {}
                      target:
                        entity_id: !input water_heater
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: normal
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_normal_day
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_off
                      data: {}
                      target:
                        entity_id: !input water_heater
    else:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: ref_appreciation
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_night_lower
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_off
                      data: {}
                      target:
                        entity_id: !input water_heater
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: appreciation
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_night_higher
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_on
                      data: {}
                      target:
                        entity_id: !input water_heater
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: ref_challenge
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_night_anchor
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_on
                      data: {}
                      target:
                        entity_id: !input water_heater
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: challenge
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_challenge
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_off
                      data: {}
                      target:
                        entity_id: !input water_heater
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: preheat
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_preheat
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_on
                      data: {}
                      target:
                        entity_id: !input water_heater
          - conditions:
              - condition: state
                entity_id: !input challenge_entity
                state: normal
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: !input scenes_normal_night
                metadata: {}
              - choose:
                - conditions: "{{ water_heater|length > 0 }}"
                  sequence:
                    - service: switch.turn_off
                      data: {}
                      target:
                        entity_id: !input water_heater
mode: single
